<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ExItS.PinoyBuyNowPayLater.UnitTests</RootNamespace>
    <AssemblyName>ExItS.PinoyBuyNowPayLater.UnitTests</AssemblyName>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Products\PinoyBuyNowPayLater\ExItS.PinoyBuyNowPayLater.Api\ExItS.PinoyBuyNowPayLater.Api.csproj" />
    <ProjectReference Include="..\..\src\Products\PinoyBuyNowPayLater\ExItS.PinoyBuyNowPayLater.Application\ExItS.PinoyBuyNowPayLater.Application.csproj" />
    <ProjectReference Include="..\..\src\Products\PinoyBuyNowPayLater\ExItS.PinoyBuyNowPayLater.Domain\ExItS.PinoyBuyNowPayLater.Domain.csproj" />
    <ProjectReference Include="..\..\src\Products\PinoyBuyNowPayLater\ExItS.PinoyBuyNowPayLater.Infrastructure\ExItS.PinoyBuyNowPayLater.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
