using ExItS.PinoyBusinessPOS.Application.Common;
using ExItS.PinoyBusinessPOS.Domain.Sales;

namespace ExItS.PinoyBusinessPOS.Application.Sales;

public static class SalesDocumentWording
{
    public const string TransactionSummary = "TransactionSummary";
    public const string DisclaimerEnglish =
        "This transaction summary is generated by ExItS for business and customer record purposes. " +
        "It is not represented by ExItS as a BIR-authorized tax invoice.";
}

public sealed class RequestSalesDocument
{
    public ApplicationResult Execute(SalesDocumentKind kind) =>
        kind == SalesDocumentKind.TransactionSummary
            ? ApplicationResult.Success()
            : ApplicationResult.Failure(
                ApplicationErrorCodes.TaxDocumentIssuanceNotAvailable,
                "Tax-document issuance is not available for this organization.");
}
