// <auto-generated />
using System;
using ExItS.Platform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExItS.Platform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260729191447_AddEntitlementSnapshotsAndOverrides")]
    partial class AddEntitlementSnapshotsAndOverrides
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("platform")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Catalog.FeatureDefinitionRecord", b =>
                {
                    b.Property<string>("ProductCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("product_code");

                    b.Property<string>("FeatureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("feature_code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("value_type");

                    b.HasKey("ProductCode", "FeatureCode");

                    b.ToTable("feature_definitions", "platform");
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Catalog.PlanRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("product_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode", "Code")
                        .IsUnique();

                    b.ToTable("plans", "platform");
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Catalog.PlanVersionFeatureGrantRecord", b =>
                {
                    b.Property<Guid>("PlanVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_version_id");

                    b.Property<string>("FeatureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("feature_code");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int?>("NumericLimit")
                        .HasColumnType("integer")
                        .HasColumnName("numeric_limit");

                    b.HasKey("PlanVersionId", "FeatureCode");

                    b.ToTable("plan_version_feature_grants", "platform");
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Catalog.PlanVersionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("billing_period");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("product_code");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<bool>("TrialEligible")
                        .HasColumnType("boolean")
                        .HasColumnName("trial_eligible");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("plan_versions", "platform");
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Catalog.ProductRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("products", "platform");
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Catalog.TrialDefinitionFeatureGrantRecord", b =>
                {
                    b.Property<Guid>("TrialDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("trial_definition_id");

                    b.Property<string>("FeatureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("feature_code");

                    b.Property<string>("GrantKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("grant_kind");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int?>("NumericLimit")
                        .HasColumnType("integer")
                        .HasColumnName("numeric_limit");

                    b.HasKey("TrialDefinitionId", "FeatureCode", "GrantKind");

                    b.ToTable("trial_definition_feature_grants", "platform");
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Catalog.TrialDefinitionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ticks");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("product_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("trial_definitions", "platform");
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Entitlements.EntitlementSnapshotGrantRecord", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("FeatureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("feature_code");

                    b.Property<DateTimeOffset>("EffectiveAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at_utc");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<int?>("NumericLimit")
                        .HasColumnType("integer")
                        .HasColumnName("numeric_limit");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.HasKey("SnapshotId", "FeatureCode");

                    b.ToTable("entitlement_snapshot_grants", "platform");
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Entitlements.EntitlementSnapshotRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("EffectiveAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at_utc");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at_utc");

                    b.Property<bool>("InGracePeriod")
                        .HasColumnType("boolean")
                        .HasColumnName("in_grace_period");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("plan_code");

                    b.Property<int>("PlanVersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("plan_version_number");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("product_code");

                    b.Property<DateTimeOffset>("RefreshByUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_by_utc");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<int>("SnapshotVersion")
                        .HasColumnType("integer")
                        .HasColumnName("snapshot_version");

                    b.Property<int>("SourceAggregateVersion")
                        .HasColumnType("integer")
                        .HasColumnName("source_aggregate_version");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("subscription_status");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("OrganizationId", "ProductCode", "SnapshotVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_entitlement_snapshots_org_product_version");

                    b.ToTable("entitlement_snapshots", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_entitlement_snapshots_expiry_range", "expires_at_utc IS NULL OR expires_at_utc >= effective_at_utc");

                            t.HasCheckConstraint("ck_entitlement_snapshots_refresh_range", "refresh_by_utc >= generated_at_utc");

                            t.HasCheckConstraint("ck_entitlement_snapshots_schema_positive", "schema_version > 0");

                            t.HasCheckConstraint("ck_entitlement_snapshots_version_positive", "snapshot_version > 0");
                        });
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Entitlements.FeatureOverrideRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from_utc");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("FeatureCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("feature_code");

                    b.Property<int?>("NumericLimit")
                        .HasColumnType("integer")
                        .HasColumnName("numeric_limit");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("product_code");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("reason");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ProductCode", "FeatureCode");

                    b.ToTable("feature_overrides", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_feature_overrides_expiry_range", "expires_at_utc IS NULL OR expires_at_utc > effective_from_utc");

                            t.HasCheckConstraint("ck_feature_overrides_numeric_limit", "numeric_limit IS NULL OR numeric_limit >= 0");
                        });
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Organizations.PlatformOrganizationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("organizations", "platform");
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Payments.SaaSPaymentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AggregateVersion")
                        .HasColumnType("integer")
                        .HasColumnName("aggregate_version");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at_utc");

                    b.Property<string>("ConfirmedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("confirmed_by");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency_code")
                        .IsFixedLength();

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("external_reference");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("method");

                    b.Property<string>("NormalizedReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("normalized_reference");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at_utc");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("product_code");

                    b.Property<DateTimeOffset?>("RejectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at_utc");

                    b.Property<string>("RejectedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("rejected_by");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("void_reason");

                    b.Property<DateTimeOffset?>("VoidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at_utc");

                    b.Property<string>("VoidedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("voided_by");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("Method", "NormalizedReference", "OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_saas_payments_reference")
                        .HasFilter("status NOT IN ('Rejected', 'Voided')");

                    b.ToTable("saas_payments", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_saas_payments_positive_amount", "amount > 0");
                        });
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Subscriptions.SubscriptionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AggregateVersion")
                        .HasColumnType("integer")
                        .HasColumnName("aggregate_version");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("ExpiredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at_utc");

                    b.Property<DateTimeOffset?>("GracePeriodEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("grace_period_end_utc");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("PaidPeriodEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_period_end_utc");

                    b.Property<DateTimeOffset?>("PaidPeriodStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_period_start_utc");

                    b.Property<DateTimeOffset?>("PastDueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("past_due_at_utc");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid>("PlanVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_version_id");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("product_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SuspendedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at_utc");

                    b.Property<Guid?>("TrialDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("trial_definition_id");

                    b.Property<DateTimeOffset?>("TrialEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_end_utc");

                    b.Property<DateTimeOffset?>("TrialStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_start_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("PlanVersionId");

                    b.HasIndex("TrialDefinitionId");

                    b.HasIndex("OrganizationId", "ProductCode")
                        .IsUnique()
                        .HasDatabaseName("ux_subscriptions_one_active_like")
                        .HasFilter("status IN ('Trialing', 'Active', 'GracePeriod', 'PastDue', 'Suspended')");

                    b.ToTable("subscriptions", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_subscriptions_paid_range", "paid_period_start_utc IS NULL OR paid_period_end_utc IS NULL OR paid_period_end_utc > paid_period_start_utc");

                            t.HasCheckConstraint("ck_subscriptions_trial_range", "trial_start_utc IS NULL OR trial_end_utc IS NULL OR trial_end_utc > trial_start_utc");
                        });
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Catalog.PlanVersionFeatureGrantRecord", b =>
                {
                    b.HasOne("ExItS.Platform.Infrastructure.Persistence.Catalog.PlanVersionRecord", "PlanVersion")
                        .WithMany("FeatureGrants")
                        .HasForeignKey("PlanVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanVersion");
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Catalog.PlanVersionRecord", b =>
                {
                    b.HasOne("ExItS.Platform.Infrastructure.Persistence.Catalog.PlanRecord", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Catalog.TrialDefinitionFeatureGrantRecord", b =>
                {
                    b.HasOne("ExItS.Platform.Infrastructure.Persistence.Catalog.TrialDefinitionRecord", "TrialDefinition")
                        .WithMany("FeatureGrants")
                        .HasForeignKey("TrialDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrialDefinition");
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Entitlements.EntitlementSnapshotGrantRecord", b =>
                {
                    b.HasOne("ExItS.Platform.Infrastructure.Persistence.Entitlements.EntitlementSnapshotRecord", "Snapshot")
                        .WithMany("Grants")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Entitlements.EntitlementSnapshotRecord", b =>
                {
                    b.HasOne("ExItS.Platform.Infrastructure.Persistence.Organizations.PlatformOrganizationRecord", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExItS.Platform.Infrastructure.Persistence.Subscriptions.SubscriptionRecord", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Entitlements.FeatureOverrideRecord", b =>
                {
                    b.HasOne("ExItS.Platform.Infrastructure.Persistence.Organizations.PlatformOrganizationRecord", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Payments.SaaSPaymentRecord", b =>
                {
                    b.HasOne("ExItS.Platform.Infrastructure.Persistence.Organizations.PlatformOrganizationRecord", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExItS.Platform.Infrastructure.Persistence.Subscriptions.SubscriptionRecord", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Subscriptions.SubscriptionRecord", b =>
                {
                    b.HasOne("ExItS.Platform.Infrastructure.Persistence.Organizations.PlatformOrganizationRecord", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExItS.Platform.Infrastructure.Persistence.Catalog.PlanRecord", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExItS.Platform.Infrastructure.Persistence.Catalog.PlanVersionRecord", null)
                        .WithMany()
                        .HasForeignKey("PlanVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExItS.Platform.Infrastructure.Persistence.Catalog.TrialDefinitionRecord", null)
                        .WithMany()
                        .HasForeignKey("TrialDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Catalog.PlanVersionRecord", b =>
                {
                    b.Navigation("FeatureGrants");
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Catalog.TrialDefinitionRecord", b =>
                {
                    b.Navigation("FeatureGrants");
                });

            modelBuilder.Entity("ExItS.Platform.Infrastructure.Persistence.Entitlements.EntitlementSnapshotRecord", b =>
                {
                    b.Navigation("Grants");
                });
#pragma warning restore 612, 618
        }
    }
}
