// <auto-generated />
using ExItS.Platform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ExItS.Platform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260917120000_AddOrganizationOnlineSupplierPaymentsCapabilities")]
    partial class AddOrganizationOnlineSupplierPaymentsCapabilities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Hand-authored SQL migration; PlatformDbContextModelSnapshot is authoritative.
#pragma warning restore 612, 618
        }
    }
}
