<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ExItS.Platform.UnitTests</RootNamespace>
    <AssemblyName>ExItS.Platform.UnitTests</AssemblyName>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Platform\ExItS.Platform.Api\ExItS.Platform.Api.csproj" />
    <ProjectReference Include="..\..\src\Platform\ExItS.Platform.Application\ExItS.Platform.Application.csproj" />
    <ProjectReference Include="..\..\src\Platform\ExItS.Platform.Domain\ExItS.Platform.Domain.csproj" />
    <ProjectReference Include="..\..\src\Platform\ExItS.Platform.Infrastructure\ExItS.Platform.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
