<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ExItS.PinoyLoanManager.Domain</RootNamespace>
    <AssemblyName>ExItS.PinoyLoanManager.Domain</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ExItS.PinoyLoanManager.Infrastructure" />
    <InternalsVisibleTo Include="ExItS.PinoyLoanManager.UnitTests" />
  </ItemGroup>

</Project>
