<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ExItS.PinoyPawnManager.UnitTests</RootNamespace>
    <AssemblyName>ExItS.PinoyPawnManager.UnitTests</AssemblyName>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Products\PinoyPawnManager\ExItS.PinoyPawnManager.Api\ExItS.PinoyPawnManager.Api.csproj" />
    <ProjectReference Include="..\..\src\Products\PinoyPawnManager\ExItS.PinoyPawnManager.Application\ExItS.PinoyPawnManager.Application.csproj" />
    <ProjectReference Include="..\..\src\Products\PinoyPawnManager\ExItS.PinoyPawnManager.Domain\ExItS.PinoyPawnManager.Domain.csproj" />
    <ProjectReference Include="..\..\src\Products\PinoyPawnManager\ExItS.PinoyPawnManager.Infrastructure\ExItS.PinoyPawnManager.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
