import {
  BusinessDocument,
  DocumentFooter,
  DocumentHeader,
  DocumentMetadata,
  DocumentTotals,
  type BusinessIdentity,
  type DocumentHeaderVisibility,
} from "@/components/exits/business-document";
import type { OrganizationDocumentSettings } from "@/features/documents/document-settings";
import { formatMoney } from "@/features/documents/use-business-document-identity";

export type SalesSummaryDocumentModel = {
  dateRangeLabel: string;
  generatedBy?: string | null;
  grossSales?: number | null;
  discounts?: number | null;
  returns?: number | null;
  netSales?: number | null;
  transactionCount?: number | null;
  utang?: number | null;
  paymentBreakdown?: Array<{ label: string; amount: number }>;
};

/**
 * Management Sales Summary report content inside the shared business document shell.
 * Not mixed with individual sale Customer Purchase Summary documents.
 */
export function SalesSummaryBusinessDocument({
  model,
  settings,
  identity,
  headerVisibility,
  preview = true,
}: {
  model: SalesSummaryDocumentModel;
  settings: OrganizationDocumentSettings;
  identity: BusinessIdentity;
  headerVisibility: DocumentHeaderVisibility;
  preview?: boolean;
}) {
  const contactParts = [
    settings.footer.showBusinessContact ? identity.phone?.trim() : null,
    settings.footer.showBusinessContact ? identity.email?.trim() : null,
  ].filter(Boolean);

  return (
    <BusinessDocument preview={preview} testId="sales-summary-business-document">
      <DocumentHeader
        identity={identity}
        visibility={headerVisibility}
        title={settings.salesSummary.title}
        referenceNumber={model.dateRangeLabel}
        dateLabel={new Date().toLocaleString()}
      />
      <DocumentMetadata
        items={[
          {
            key: "branch",
            label: "Branch",
            value: headerVisibility.showBranchName ? identity.branchName : null,
          },
          { key: "generatedBy", label: "Generated by", value: model.generatedBy },
          { key: "range", label: "Date range", value: model.dateRangeLabel },
        ]}
      />
      <DocumentTotals
        rows={[
          ...(model.grossSales != null
            ? [{ key: "gross", label: "Gross sales", value: formatMoney(model.grossSales) }]
            : []),
          ...(model.discounts != null
            ? [{ key: "discounts", label: "Discounts", value: formatMoney(model.discounts) }]
            : []),
          ...(model.returns != null
            ? [{ key: "returns", label: "Returns", value: formatMoney(model.returns) }]
            : []),
          ...(model.netSales != null
            ? [
                {
                  key: "net",
                  label: "Net sales",
                  value: formatMoney(model.netSales),
                  emphasize: true,
                },
              ]
            : []),
          ...(model.utang != null
            ? [{ key: "utang", label: "Utang", value: formatMoney(model.utang) }]
            : []),
          ...(model.transactionCount != null
            ? [
                {
                  key: "count",
                  label: "Transaction count",
                  value: String(model.transactionCount),
                },
              ]
            : []),
          ...(model.paymentBreakdown ?? []).map((row) => ({
            key: `pay-${row.label}`,
            label: row.label,
            value: formatMoney(row.amount),
          })),
        ]}
      />
      <DocumentFooter
        showCustomFooter={settings.footer.showCustomFooter}
        customText={settings.footer.customFooterText}
        showBusinessContact={settings.footer.showBusinessContact}
        contactLine={contactParts.join(" · ") || null}
        showPageNumber={settings.footer.showPageNumber}
        disclaimer={null}
      />
    </BusinessDocument>
  );
}
