import { PLATFORM_PERMISSIONS } from "@/api/authorization/authorization-types";
import type { NavigationSectionDefinition } from "@/lib/navigation/navigation-types";

const P = PLATFORM_PERMISSIONS;

export const navigationRegistry: NavigationSectionDefinition[] = [
  {
    id: "home",
    labelKey: "nav.group.home",
    order: 1,
    items: [
      {
        id: "PWEB-NAV-OVERVIEW",
        labelKey: "nav.overview",
        icon: "layout-dashboard",
        href: "/admin",
        lifecycle: "AVAILABLE",
        permission: { kind: "authenticated" },
        order: 1,
      },
    ],
  },
  {
    id: "organizations",
    labelKey: "nav.group.organizations",
    order: 2,
    items: [
      {
        id: "PWEB-NAV-ALL-ORGANIZATIONS",
        labelKey: "nav.allOrganizations",
        icon: "building-2",
        href: "/admin/organizations",
        lifecycle: "AVAILABLE",
        permission: { kind: "any", codes: [P.viewPortfolio, P.manageOrganizations] },
        order: 1,
      },
      {
        id: "PWEB-NAV-BY-PRODUCT",
        labelKey: "nav.byProduct",
        icon: "boxes",
        lifecycle: "AVAILABLE",
        permission: { kind: "any", codes: [P.viewPortfolio, P.manageOrganizations] },
        order: 2,
        kind: "group",
      },
    ],
  },
  {
    id: "people",
    labelKey: "nav.group.people",
    order: 3,
    items: [
      {
        id: "PWEB-NAV-ALL-ACCOUNTS",
        labelKey: "nav.allAccounts",
        icon: "users",
        href: "/admin/users",
        lifecycle: "AVAILABLE",
        permission: { kind: "any", codes: [P.managePlatformUsers] },
        order: 1,
      },
      {
        id: "PWEB-NAV-PLATFORM-STAFF",
        labelKey: "nav.platformStaff",
        icon: "shield-check",
        href: "/admin/users?directory=PlatformStaff",
        lifecycle: "AVAILABLE",
        permission: { kind: "any", codes: [P.managePlatformUsers] },
        order: 2,
      },
      {
        id: "PWEB-NAV-ORG-ACCOUNTS",
        labelKey: "nav.orgAccounts",
        icon: "building",
        href: "/admin/users?directory=Organization",
        lifecycle: "AVAILABLE",
        permission: { kind: "any", codes: [P.managePlatformUsers] },
        order: 3,
      },
      {
        id: "PWEB-NAV-PERSONAL-ACCOUNTS",
        labelKey: "nav.personalAccounts",
        icon: "user",
        href: "/admin/users?directory=Personal",
        lifecycle: "AVAILABLE",
        permission: { kind: "any", codes: [P.managePlatformUsers] },
        order: 4,
      },
      {
        id: "PWEB-NAV-NEEDS-REVIEW",
        labelKey: "nav.needsReview",
        icon: "alert-circle",
        href: "/admin/users?directory=Unassigned",
        lifecycle: "AVAILABLE",
        permission: { kind: "any", codes: [P.managePlatformUsers] },
        order: 5,
      },
      {
        id: "PWEB-NAV-MEMBERSHIPS",
        labelKey: "nav.memberships",
        icon: "user-plus",
        href: "/admin/organization-users",
        lifecycle: "AVAILABLE",
        permission: { kind: "any", codes: [P.manageMemberships] },
        order: 6,
      },
      {
        id: "PWEB-NAV-ROLES-PERMISSIONS",
        labelKey: "nav.roles",
        icon: "key",
        href: "/admin/platform-roles",
        lifecycle: "AVAILABLE",
        permission: { kind: "any", codes: [P.managePlatformUsers] },
        order: 7,
      },
    ],
  },
  {
    id: "products",
    labelKey: "nav.group.products",
    order: 4,
    items: [
      {
        id: "PWEB-NAV-PRODUCTS",
        labelKey: "nav.products",
        icon: "package",
        href: "/admin/products",
        lifecycle: "AVAILABLE",
        permission: { kind: "any", codes: [P.viewPortfolio] },
        order: 1,
      },
      {
        id: "PWEB-NAV-PLANS",
        labelKey: "nav.plans",
        icon: "credit-card",
        href: "/admin/plans",
        lifecycle: "AVAILABLE",
        permission: { kind: "any", codes: [P.viewPortfolio] },
        order: 2,
      },
      {
        id: "PWEB-NAV-SUBSCRIPTIONS",
        labelKey: "nav.subscriptions",
        icon: "repeat",
        href: "/admin/subscriptions",
        lifecycle: "AVAILABLE",
        permission: { kind: "any", codes: [P.manageSubscriptions] },
        order: 3,
      },
      {
        id: "PWEB-NAV-ENTITLEMENTS",
        labelKey: "nav.entitlements",
        icon: "check-square",
        href: "/admin/entitlements",
        lifecycle: "AVAILABLE",
        permission: {
          kind: "any",
          codes: [P.manageEntitlementOverrides, P.manageSubscriptions, P.viewPortfolio],
        },
        order: 4,
      },
      {
        id: "PWEB-NAV-PERSONAL-FEATURES",
        labelKey: "nav.personalFeatures",
        icon: "star",
        href: "/admin/personal-features",
        lifecycle: "AVAILABLE",
        permission: { kind: "any", codes: [P.viewPortfolio] },
        order: 5,
      },
    ],
  },
  {
    id: "billing",
    labelKey: "nav.group.billing",
    order: 5,
    items: [
      {
        id: "PWEB-NAV-PAYMENTS",
        labelKey: "nav.payments",
        icon: "receipt",
        href: "/admin/payments",
        lifecycle: "AVAILABLE",
        permission: { kind: "any", codes: [P.manageManualPayments] },
        order: 1,
      },
    ],
  },
  {
    id: "catalog",
    labelKey: "nav.group.catalog",
    order: 6,
    items: [
      {
        id: "PWEB-NAV-BUSINESS-TYPES",
        labelKey: "nav.businessTypes",
        icon: "tag",
        href: "/admin/global-catalog/business-types",
        lifecycle: "AVAILABLE",
        permission: { kind: "any", codes: [P.viewGlobalCatalog] },
        order: 1,
      },
      {
        id: "PWEB-NAV-CATEGORIES",
        labelKey: "nav.categories",
        icon: "folder",
        href: "/admin/global-catalog/categories",
        lifecycle: "AVAILABLE",
        permission: { kind: "any", codes: [P.viewGlobalCatalog] },
        order: 2,
      },
      {
        id: "PWEB-NAV-GLOBAL-PRODUCTS",
        labelKey: "nav.globalProducts",
        icon: "box",
        href: "/admin/global-catalog/products",
        lifecycle: "AVAILABLE",
        permission: { kind: "any", codes: [P.viewGlobalCatalog] },
        order: 3,
      },
      {
        id: "PWEB-NAV-TEMPLATES",
        labelKey: "nav.templates",
        icon: "file-text",
        href: "/admin/catalog/templates",
        lifecycle: "AVAILABLE",
        permission: { kind: "any", codes: [P.viewGlobalCatalog] },
        order: 4,
      },
      {
        id: "PWEB-NAV-IMPORTS",
        labelKey: "nav.imports",
        icon: "upload",
        href: "/admin/catalog/imports",
        lifecycle: "AVAILABLE",
        permission: { kind: "any", codes: [P.viewGlobalCatalog] },
        order: 5,
      },
    ],
  },
  {
    id: "governance",
    labelKey: "nav.group.governance",
    order: 7,
    items: [
      {
        id: "PWEB-NAV-AUDIT-LOG",
        labelKey: "nav.auditLog",
        icon: "scroll-text",
        href: "/admin/audit",
        lifecycle: "AVAILABLE",
        permission: { kind: "any", codes: [P.viewAuditRecords] },
        order: 1,
      },
      {
        id: "PWEB-NAV-PRIVACY-COMPLIANCE",
        labelKey: "nav.privacy",
        icon: "shield",
        href: "/admin/privacy-compliance",
        lifecycle: "AVAILABLE",
        permission: { kind: "any", codes: [P.viewPrivacyCompliance] },
        order: 2,
      },
    ],
  },
  {
    id: "operations",
    labelKey: "nav.group.operations",
    order: 8,
    items: [
      {
        id: "PWEB-NAV-PLATFORM-HEALTH",
        labelKey: "nav.platformHealth",
        icon: "activity",
        href: "/admin/operations/health",
        lifecycle: "AVAILABLE",
        permission: { kind: "platformAdministrator" },
        order: 1,
      },
      {
        id: "PWEB-NAV-EVENT-DELIVERY",
        labelKey: "nav.eventDelivery",
        icon: "send",
        lifecycle: "PLANNED_DISABLED",
        permission: { kind: "platformAdministrator" },
        order: 2,
      },
    ],
  },
  {
    id: "settings",
    labelKey: "nav.group.settings",
    order: 9,
    items: [
      {
        id: "PWEB-NAV-PLATFORM-SETTINGS",
        labelKey: "nav.platformSettings",
        icon: "settings",
        lifecycle: "PLANNED_DISABLED",
        permission: { kind: "platformAdministrator" },
        order: 1,
      },
    ],
  },
  {
    id: "development",
    labelKey: "nav.group.development",
    order: 10,
    items: [
      {
        id: "PWEB-NAV-TEST-PAYMENTS",
        labelKey: "nav.testPayments",
        icon: "flask-conical",
        href: "/admin/local-validation/test-payments",
        lifecycle: "DEV_TEST_ONLY",
        permission: { kind: "any", codes: [P.manageSubscriptions] },
        order: 1,
      },
    ],
  },
];
