namespace ExItS.Platform.Domain.Geography;

/// <summary>
/// One ISO 3166-1 country. Products read this catalog through the geography API.
/// </summary>
public sealed record Country(string Code, string Name, bool IsActive);

/// <summary>
/// Authoritative country list for every ExItS product.
/// </summary>
public static class CountryCatalog
{
    public static IReadOnlyList<Country> All { get; } =
    [
        new("AF", "Afghanistan", true),
        new("AX", "Åland Islands", true),
        new("AL", "Albania", true),
        new("DZ", "Algeria", true),
        new("AS", "American Samoa", true),
        new("AD", "Andorra", true),
        new("AO", "Angola", true),
        new("AI", "Anguilla", true),
        new("AQ", "Antarctica", true),
        new("AG", "Antigua & Barbuda", true),
        new("AR", "Argentina", true),
        new("AM", "Armenia", true),
        new("AW", "Aruba", true),
        new("AU", "Australia", true),
        new("AT", "Austria", true),
        new("AZ", "Azerbaijan", true),
        new("BS", "Bahamas", true),
        new("BH", "Bahrain", true),
        new("BD", "Bangladesh", true),
        new("BB", "Barbados", true),
        new("BY", "Belarus", true),
        new("BE", "Belgium", true),
        new("BZ", "Belize", true),
        new("BJ", "Benin", true),
        new("BM", "Bermuda", true),
        new("BT", "Bhutan", true),
        new("BO", "Bolivia", true),
        new("BQ", "Caribbean Netherlands", true),
        new("BA", "Bosnia & Herzegovina", true),
        new("BW", "Botswana", true),
        new("BV", "Bouvet Island", true),
        new("BR", "Brazil", true),
        new("IO", "British Indian Ocean Territory", true),
        new("BN", "Brunei", true),
        new("BG", "Bulgaria", true),
        new("BF", "Burkina Faso", true),
        new("BI", "Burundi", true),
        new("CV", "Cape Verde", true),
        new("KH", "Cambodia", true),
        new("CM", "Cameroon", true),
        new("CA", "Canada", true),
        new("KY", "Cayman Islands", true),
        new("CF", "Central African Republic", true),
        new("TD", "Chad", true),
        new("CL", "Chile", true),
        new("CN", "China", true),
        new("CX", "Christmas Island", true),
        new("CC", "Cocos (Keeling) Islands", true),
        new("CO", "Colombia", true),
        new("KM", "Comoros", true),
        new("CG", "Congo - Brazzaville", true),
        new("CD", "Congo - Kinshasa", true),
        new("CK", "Cook Islands", true),
        new("CR", "Costa Rica", true),
        new("CI", "Côte d’Ivoire", true),
        new("HR", "Croatia", true),
        new("CU", "Cuba", true),
        new("CW", "Curaçao", true),
        new("CY", "Cyprus", true),
        new("CZ", "Czechia", true),
        new("DK", "Denmark", true),
        new("DJ", "Djibouti", true),
        new("DM", "Dominica", true),
        new("DO", "Dominican Republic", true),
        new("EC", "Ecuador", true),
        new("EG", "Egypt", true),
        new("SV", "El Salvador", true),
        new("GQ", "Equatorial Guinea", true),
        new("ER", "Eritrea", true),
        new("EE", "Estonia", true),
        new("SZ", "Eswatini", true),
        new("ET", "Ethiopia", true),
        new("FK", "Falkland Islands", true),
        new("FO", "Faroe Islands", true),
        new("FJ", "Fiji", true),
        new("FI", "Finland", true),
        new("FR", "France", true),
        new("GF", "French Guiana", true),
        new("PF", "French Polynesia", true),
        new("TF", "French Southern Territories", true),
        new("GA", "Gabon", true),
        new("GM", "Gambia", true),
        new("GE", "Georgia", true),
        new("DE", "Germany", true),
        new("GH", "Ghana", true),
        new("GI", "Gibraltar", true),
        new("GR", "Greece", true),
        new("GL", "Greenland", true),
        new("GD", "Grenada", true),
        new("GP", "Guadeloupe", true),
        new("GU", "Guam", true),
        new("GT", "Guatemala", true),
        new("GG", "Guernsey", true),
        new("GN", "Guinea", true),
        new("GW", "Guinea-Bissau", true),
        new("GY", "Guyana", true),
        new("HT", "Haiti", true),
        new("HM", "Heard & McDonald Islands", true),
        new("VA", "Vatican City", true),
        new("HN", "Honduras", true),
        new("HK", "Hong Kong SAR China", true),
        new("HU", "Hungary", true),
        new("IS", "Iceland", true),
        new("IN", "India", true),
        new("ID", "Indonesia", true),
        new("IR", "Iran", true),
        new("IQ", "Iraq", true),
        new("IE", "Ireland", true),
        new("IM", "Isle of Man", true),
        new("IL", "Israel", true),
        new("IT", "Italy", true),
        new("JM", "Jamaica", true),
        new("JP", "Japan", true),
        new("JE", "Jersey", true),
        new("JO", "Jordan", true),
        new("KZ", "Kazakhstan", true),
        new("KE", "Kenya", true),
        new("KI", "Kiribati", true),
        new("KP", "North Korea", true),
        new("KR", "South Korea", true),
        new("KW", "Kuwait", true),
        new("KG", "Kyrgyzstan", true),
        new("LA", "Laos", true),
        new("LV", "Latvia", true),
        new("LB", "Lebanon", true),
        new("LS", "Lesotho", true),
        new("LR", "Liberia", true),
        new("LY", "Libya", true),
        new("LI", "Liechtenstein", true),
        new("LT", "Lithuania", true),
        new("LU", "Luxembourg", true),
        new("MO", "Macao SAR China", true),
        new("MG", "Madagascar", true),
        new("MW", "Malawi", true),
        new("MY", "Malaysia", true),
        new("MV", "Maldives", true),
        new("ML", "Mali", true),
        new("MT", "Malta", true),
        new("MH", "Marshall Islands", true),
        new("MQ", "Martinique", true),
        new("MR", "Mauritania", true),
        new("MU", "Mauritius", true),
        new("YT", "Mayotte", true),
        new("MX", "Mexico", true),
        new("FM", "Micronesia", true),
        new("MD", "Moldova", true),
        new("MC", "Monaco", true),
        new("MN", "Mongolia", true),
        new("ME", "Montenegro", true),
        new("MS", "Montserrat", true),
        new("MA", "Morocco", true),
        new("MZ", "Mozambique", true),
        new("MM", "Myanmar (Burma)", true),
        new("NA", "Namibia", true),
        new("NR", "Nauru", true),
        new("NP", "Nepal", true),
        new("NL", "Netherlands", true),
        new("NC", "New Caledonia", true),
        new("NZ", "New Zealand", true),
        new("NI", "Nicaragua", true),
        new("NE", "Niger", true),
        new("NG", "Nigeria", true),
        new("NU", "Niue", true),
        new("NF", "Norfolk Island", true),
        new("MK", "North Macedonia", true),
        new("MP", "Northern Mariana Islands", true),
        new("NO", "Norway", true),
        new("OM", "Oman", true),
        new("PK", "Pakistan", true),
        new("PW", "Palau", true),
        new("PS", "Palestinian Territories", true),
        new("PA", "Panama", true),
        new("PG", "Papua New Guinea", true),
        new("PY", "Paraguay", true),
        new("PE", "Peru", true),
        new("PH", "Philippines", true),
        new("PN", "Pitcairn Islands", true),
        new("PL", "Poland", true),
        new("PT", "Portugal", true),
        new("PR", "Puerto Rico", true),
        new("QA", "Qatar", true),
        new("RE", "Réunion", true),
        new("RO", "Romania", true),
        new("RU", "Russia", true),
        new("RW", "Rwanda", true),
        new("BL", "St. Barthélemy", true),
        new("SH", "St. Helena", true),
        new("KN", "St. Kitts & Nevis", true),
        new("LC", "St. Lucia", true),
        new("MF", "St. Martin", true),
        new("PM", "St. Pierre & Miquelon", true),
        new("VC", "St. Vincent & Grenadines", true),
        new("WS", "Samoa", true),
        new("SM", "San Marino", true),
        new("ST", "São Tomé & Príncipe", true),
        new("SA", "Saudi Arabia", true),
        new("SN", "Senegal", true),
        new("RS", "Serbia", true),
        new("SC", "Seychelles", true),
        new("SL", "Sierra Leone", true),
        new("SG", "Singapore", true),
        new("SX", "Sint Maarten", true),
        new("SK", "Slovakia", true),
        new("SI", "Slovenia", true),
        new("SB", "Solomon Islands", true),
        new("SO", "Somalia", true),
        new("ZA", "South Africa", true),
        new("GS", "South Georgia & South Sandwich Islands", true),
        new("SS", "South Sudan", true),
        new("ES", "Spain", true),
        new("LK", "Sri Lanka", true),
        new("SD", "Sudan", true),
        new("SR", "Suriname", true),
        new("SJ", "Svalbard & Jan Mayen", true),
        new("SE", "Sweden", true),
        new("CH", "Switzerland", true),
        new("SY", "Syria", true),
        new("TW", "Taiwan", true),
        new("TJ", "Tajikistan", true),
        new("TZ", "Tanzania", true),
        new("TH", "Thailand", true),
        new("TL", "Timor-Leste", true),
        new("TG", "Togo", true),
        new("TK", "Tokelau", true),
        new("TO", "Tonga", true),
        new("TT", "Trinidad & Tobago", true),
        new("TN", "Tunisia", true),
        new("TR", "Türkiye", true),
        new("TM", "Turkmenistan", true),
        new("TC", "Turks & Caicos Islands", true),
        new("TV", "Tuvalu", true),
        new("UG", "Uganda", true),
        new("UA", "Ukraine", true),
        new("AE", "United Arab Emirates", true),
        new("GB", "United Kingdom", true),
        new("US", "United States", true),
        new("UM", "U.S. Outlying Islands", true),
        new("UY", "Uruguay", true),
        new("UZ", "Uzbekistan", true),
        new("VU", "Vanuatu", true),
        new("VE", "Venezuela", true),
        new("VN", "Vietnam", true),
        new("VG", "British Virgin Islands", true),
        new("VI", "U.S. Virgin Islands", true),
        new("WF", "Wallis & Futuna", true),
        new("EH", "Western Sahara", true),
        new("YE", "Yemen", true),
        new("ZM", "Zambia", true),
        new("ZW", "Zimbabwe", true),
    ];

    private static readonly Dictionary<string, Country> ByCode = All.ToDictionary(
        country => country.Code,
        StringComparer.OrdinalIgnoreCase);

    private static readonly Dictionary<string, Country> ByName = All.ToDictionary(
        country => country.Name,
        StringComparer.OrdinalIgnoreCase);

    public static Country? Find(string? codeOrName)
    {
        if (string.IsNullOrWhiteSpace(codeOrName))
        {
            return null;
        }

        var key = codeOrName.Trim();
        if (ByCode.TryGetValue(key, out var byCode))
        {
            return byCode;
        }

        return ByName.TryGetValue(key, out var byName) ? byName : null;
    }

    public static bool IsPhilippines(string? codeOrName) =>
        string.Equals(Find(codeOrName)?.Code, "PH", StringComparison.OrdinalIgnoreCase);
}
