// <auto-generated />
using System;
using ExItS.PinoyBusinessPOS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExItS.PinoyBusinessPOS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PosDbContext))]
    [Migration("20260730084848_AddPosRepayments")]
    partial class AddPosRepayments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pos")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExItS.PinoyBusinessPOS.Infrastructure.Persistence.Credit.CreditEntryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("remarks");

                    b.Property<string>("ReversalReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reversal_reason");

                    b.Property<DateTimeOffset?>("ReversedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reversed_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrganizationId", "CustomerId", "CreatedAtUtc")
                        .HasDatabaseName("ix_credit_entries_org_customer_created");

                    b.HasIndex("OrganizationId", "CustomerId", "Status")
                        .HasDatabaseName("ix_credit_entries_org_customer_status");

                    b.ToTable("credit_entries", "pos", t =>
                        {
                            t.HasCheckConstraint("ck_credit_entries_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_credit_entries_status", "status IN ('Active', 'Reversed')");
                        });
                });

            modelBuilder.Entity("ExItS.PinoyBusinessPOS.Infrastructure.Persistence.Customers.POSCustomerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("NormalizedMobile")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("normalized_mobile");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_customers_organization_id");

                    b.HasIndex("OrganizationId", "DisplayName")
                        .HasDatabaseName("ix_customers_org_display_name");

                    b.HasIndex("OrganizationId", "NormalizedMobile")
                        .IsUnique()
                        .HasDatabaseName("ux_customers_org_active_mobile")
                        .HasFilter("status = 'Active' AND normalized_mobile IS NOT NULL");

                    b.ToTable("customers", "pos", t =>
                        {
                            t.HasCheckConstraint("ck_customers_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("ExItS.PinoyBusinessPOS.Infrastructure.Persistence.Payments.RepaymentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<Guid>("RecordedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by");

                    b.Property<string>("Remarks")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("remarks");

                    b.Property<string>("ReversalReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reversal_reason");

                    b.Property<DateTimeOffset?>("ReversedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reversed_at_utc");

                    b.Property<Guid?>("ReversedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reversed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_repayments_organization_id");

                    b.HasIndex("OrganizationId", "CustomerId", "RecordedAtUtc")
                        .HasDatabaseName("ix_repayments_org_customer_recorded");

                    b.HasIndex("OrganizationId", "CustomerId", "Status")
                        .HasDatabaseName("ix_repayments_org_customer_status");

                    b.ToTable("repayments", "pos", t =>
                        {
                            t.HasCheckConstraint("ck_repayments_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_repayments_reversal_consistency", "(status = 'Active' AND reversed_at_utc IS NULL AND reversal_reason IS NULL AND reversed_by IS NULL) OR (status = 'Reversed' AND reversed_at_utc IS NOT NULL AND reversal_reason IS NOT NULL AND reversed_by IS NOT NULL)");

                            t.HasCheckConstraint("ck_repayments_status", "status IN ('Active', 'Reversed')");
                        });
                });

            modelBuilder.Entity("ExItS.PinoyBusinessPOS.Infrastructure.Persistence.Credit.CreditEntryRecord", b =>
                {
                    b.HasOne("ExItS.PinoyBusinessPOS.Infrastructure.Persistence.Customers.POSCustomerRecord", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_credit_entries_customers");
                });

            modelBuilder.Entity("ExItS.PinoyBusinessPOS.Infrastructure.Persistence.Payments.RepaymentRecord", b =>
                {
                    b.HasOne("ExItS.PinoyBusinessPOS.Infrastructure.Persistence.Customers.POSCustomerRecord", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_repayments_customers");
                });
#pragma warning restore 612, 618
        }
    }
}
