// <auto-generated />
using System;
using ExItS.PinoyBuyNowPayLater.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExItS.PinoyBuyNowPayLater.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BnplDbContext))]
    [Migration("20260827111326_AddBnplFinancingApplicationLifecycle")]
    partial class AddBnplFinancingApplicationLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bnpl")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExItS.PinoyBuyNowPayLater.Infrastructure.Persistence.Customers.BnplCustomerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<Guid?>("LinkedCommerceCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_commerce_customer_id");

                    b.Property<string>("LinkedPersonalPublicUserId")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("linked_personal_public_user_id");

                    b.Property<string>("Mobile")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mobile");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedMobile")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("normalized_mobile");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_bnpl_customers_organization_id");

                    b.HasIndex("OrganizationId", "DisplayName")
                        .HasDatabaseName("ix_bnpl_customers_org_display_name");

                    b.HasIndex("OrganizationId", "LinkedCommerceCustomerId")
                        .IsUnique()
                        .HasDatabaseName("ux_bnpl_customers_org_linked_commerce")
                        .HasFilter("linked_commerce_customer_id IS NOT NULL");

                    b.HasIndex("OrganizationId", "LinkedPersonalPublicUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_bnpl_customers_org_linked_personal")
                        .HasFilter("linked_personal_public_user_id IS NOT NULL");

                    b.HasIndex("OrganizationId", "NormalizedEmail")
                        .HasDatabaseName("ix_bnpl_customers_org_normalized_email");

                    b.HasIndex("OrganizationId", "NormalizedMobile")
                        .HasDatabaseName("ix_bnpl_customers_org_normalized_mobile");

                    b.ToTable("customers", "bnpl", t =>
                        {
                            t.HasCheckConstraint("ck_bnpl_customers_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("ExItS.PinoyBuyNowPayLater.Infrastructure.Persistence.Financing.BnplFinancingApplicationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcceptedOfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_offer_id");

                    b.Property<int>("AggregateVersion")
                        .HasColumnType("integer")
                        .HasColumnName("aggregate_version");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_actor_id");

                    b.Property<Guid?>("CurrentOfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_offer_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("DownPaymentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("down_payment_amount");

                    b.Property<bool>("EligibilityApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("eligibility_approved");

                    b.Property<DateTimeOffset?>("EligibilityDecidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eligibility_decided_at_utc");

                    b.Property<Guid?>("EligibilityDecidedByActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("eligibility_decided_by_actor_id");

                    b.Property<string>("EligibilityNote")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("eligibility_note");

                    b.Property<string>("MerchantProductReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("merchant_product_reference");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<decimal>("PurchaseAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("purchase_amount");

                    b.Property<string>("PurchaseDescription")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("purchase_description");

                    b.Property<decimal>("RequestedFinanceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("requested_finance_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrganizationId", "BranchId")
                        .HasDatabaseName("ix_bnpl_financing_applications_org_branch");

                    b.HasIndex("OrganizationId", "CustomerId")
                        .HasDatabaseName("ix_bnpl_financing_applications_org_customer");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_bnpl_financing_applications_org_status");

                    b.ToTable("financing_applications", "bnpl", t =>
                        {
                            t.HasCheckConstraint("ck_bnpl_financing_applications_status", "status IN ('Draft', 'PendingEligibility', 'Offered', 'CustomerAccepted', 'ApprovedPendingSale', 'Declined', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("ExItS.PinoyBuyNowPayLater.Infrastructure.Persistence.Financing.BnplFinancingDecisionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at_utc");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("note");

                    b.Property<Guid?>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("stage");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "DecidedAtUtc")
                        .HasDatabaseName("ix_bnpl_financing_decisions_application_time");

                    b.ToTable("financing_decisions", "bnpl");
                });

            modelBuilder.Entity("ExItS.PinoyBuyNowPayLater.Infrastructure.Persistence.Financing.BnplFinancingOfferRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at_utc");

                    b.Property<Guid?>("AcceptedByActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by_actor_id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_actor_id");

                    b.Property<decimal>("DownPaymentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("down_payment_amount");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<decimal>("FinancedPrincipal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("financed_principal");

                    b.Property<bool>("IsSuperseded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_superseded");

                    b.Property<decimal>("PurchaseAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("purchase_amount");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_bnpl_financing_offers_application_version");

                    b.ToTable("financing_offers", "bnpl");
                });

            modelBuilder.Entity("ExItS.PinoyBuyNowPayLater.Infrastructure.Persistence.Financing.BnplFinancingApplicationRecord", b =>
                {
                    b.HasOne("ExItS.PinoyBuyNowPayLater.Infrastructure.Persistence.Customers.BnplCustomerRecord", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bnpl_financing_applications_customer");
                });

            modelBuilder.Entity("ExItS.PinoyBuyNowPayLater.Infrastructure.Persistence.Financing.BnplFinancingDecisionRecord", b =>
                {
                    b.HasOne("ExItS.PinoyBuyNowPayLater.Infrastructure.Persistence.Financing.BnplFinancingApplicationRecord", "Application")
                        .WithMany("Decisions")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("ExItS.PinoyBuyNowPayLater.Infrastructure.Persistence.Financing.BnplFinancingOfferRecord", b =>
                {
                    b.HasOne("ExItS.PinoyBuyNowPayLater.Infrastructure.Persistence.Financing.BnplFinancingApplicationRecord", "Application")
                        .WithMany("Offers")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("ExItS.PinoyBuyNowPayLater.Infrastructure.Persistence.Financing.BnplFinancingApplicationRecord", b =>
                {
                    b.Navigation("Decisions");

                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
