// <auto-generated />
using System;
using ExItS.PinoyBuyNowPayLater.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExItS.PinoyBuyNowPayLater.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BnplDbContext))]
    partial class BnplDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bnpl")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExItS.PinoyBuyNowPayLater.Infrastructure.Persistence.Customers.BnplCustomerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<Guid?>("LinkedCommerceCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_commerce_customer_id");

                    b.Property<string>("LinkedPersonalPublicUserId")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("linked_personal_public_user_id");

                    b.Property<string>("Mobile")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mobile");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedMobile")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("normalized_mobile");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_bnpl_customers_organization_id");

                    b.HasIndex("OrganizationId", "DisplayName")
                        .HasDatabaseName("ix_bnpl_customers_org_display_name");

                    b.HasIndex("OrganizationId", "LinkedCommerceCustomerId")
                        .IsUnique()
                        .HasDatabaseName("ux_bnpl_customers_org_linked_commerce")
                        .HasFilter("linked_commerce_customer_id IS NOT NULL");

                    b.HasIndex("OrganizationId", "LinkedPersonalPublicUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_bnpl_customers_org_linked_personal")
                        .HasFilter("linked_personal_public_user_id IS NOT NULL");

                    b.HasIndex("OrganizationId", "NormalizedEmail")
                        .HasDatabaseName("ix_bnpl_customers_org_normalized_email");

                    b.HasIndex("OrganizationId", "NormalizedMobile")
                        .HasDatabaseName("ix_bnpl_customers_org_normalized_mobile");

                    b.ToTable("customers", "bnpl", t =>
                        {
                            t.HasCheckConstraint("ck_bnpl_customers_status", "status IN ('Active', 'Inactive')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
