<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ExItS.Platform.Domain</RootNamespace>
    <AssemblyName>ExItS.Platform.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ExItS.Platform.Infrastructure" />
    <InternalsVisibleTo Include="ExItS.Platform.UnitTests" />
    <InternalsVisibleTo Include="ExItS.Platform.IntegrationTests" />
  </ItemGroup>

</Project>
