<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ExItS.Platform.Infrastructure</RootNamespace>
    <AssemblyName>ExItS.Platform.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ExItS.Platform.UnitTests" />
    <InternalsVisibleTo Include="ExItS.Platform.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="QuestPDF" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExItS.Platform.Application\ExItS.Platform.Application.csproj" />
    <ProjectReference Include="..\ExItS.Platform.Domain\ExItS.Platform.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="ReferenceData\Philippines\psgc-localities-2026-06-30.json">
      <LogicalName>ExItS.Platform.Infrastructure.ReferenceData.Philippines.psgc-localities-2026-06-30.json</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
