<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ExItS.PinoyPawnManager.Application</RootNamespace>
    <AssemblyName>ExItS.PinoyPawnManager.Application</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExItS.PinoyPawnManager.Domain\ExItS.PinoyPawnManager.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ExItS.PinoyPawnManager.UnitTests" />
  </ItemGroup>

</Project>
